---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  
      # Get the environment variables from CircleCI and add to the EC2 instance
  environment:
    - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"  
    # Add more env vars here
    - TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES')}}"
    - TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
    - TYPEORM_PORT: 5432
    - TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
    - TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
    - TYPEORM_ENTITIES: ./modules/domain/**/*.entity{.ts,.js}
    - TYPEORM_MIGRATIONS: ./migrations/.*ts
    - TYPEORM_MIGRATIONS_DIR: ./migrations
    - NODE_ENV: "{{ lookup('env', 'NODE_ENV')}}"
    - VERSION: "{{ lookup('env', 'VERSION')}}"
  
  roles:
    - deploy
